server:
  port: 8001

spring:
  application:
    name: service-hello
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
      
