server:
  port: 8881

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    config:
      label: master
      profile: dev
      discovery: 
        enabled: true
        serviceId: config-server
      #uri: http://localhost:8888/