server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/clyhs/springcloud-sample
          search-paths: springcloud-repos
          label: master
          username: 
          password: 